// <auto-generated />
using System;
using FreshlyBackendNew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshlyBackendNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429073237_MakeLaundryFieldsNullable")]
    partial class MakeLaundryFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FreshlyBackendNew.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ContactId", "ContactNumber");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.Property<Guid>("LaundryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LaundryName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("LaundryId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Laundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.LaundryItemService", b =>
                {
                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LaundryId", "ItemId", "ServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("LaundryItemServices");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PickupDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PickupTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PlacedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlacedTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderDetails", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ItemId", "ServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TypeId");

                    b.ToTable("OrderTypes");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OwnerId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Privilege", b =>
                {
                    b.Property<Guid>("PrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PrivilegeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrivilegeId");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.PrivilegeUserGroup", b =>
                {
                    b.Property<Guid>("PrivilegeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("char(36)");

                    b.HasKey("PrivilegeId", "UserGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("PrivilegeUserGroups");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Status", b =>
                {
                    b.Property<Guid>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserGroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserGroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Contact", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Owner", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithOne("Customer")
                        .HasForeignKey("FreshlyBackendNew.Models.Customer", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laundry");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithOne("Laundry")
                        .HasForeignKey("FreshlyBackendNew.Models.Laundry", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FreshlyBackendNew.Models.Owner", "Owner")
                        .WithOne("Laundry")
                        .HasForeignKey("FreshlyBackendNew.Models.Laundry", "OwnerId");

                    b.Navigation("Address");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.LaundryItemService", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany("LaundryItemServices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("LaundryItemServices")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany("LaundryItemServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Laundry");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("Orders")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laundry");

                    b.Navigation("OrderType");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderDetails", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithOne("Owner")
                        .HasForeignKey("FreshlyBackendNew.Models.Owner", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Payment", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("FreshlyBackendNew.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.PrivilegeUserGroup", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Privilege", "Privilege")
                        .WithMany("PrivilegeUserGroups")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.UserGroup", "UserGroup")
                        .WithMany("PrivilegeUserGroups")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.UserGroup", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Address", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Laundry")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.Navigation("LaundryItemServices");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Feedbacks");

                    b.Navigation("LaundryItemServices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Laundry")
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Privilege", b =>
                {
                    b.Navigation("PrivilegeUserGroups");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Service", b =>
                {
                    b.Navigation("LaundryItemServices");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroup", b =>
                {
                    b.Navigation("PrivilegeUserGroups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
