// <auto-generated />
using System;
using FreshlyBackendNew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshlyBackendNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511104805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FreshlyBackendNew.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ContactId");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LicensNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DriverId");

                    b.HasIndex("AddressId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.DriverNote", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("NoteId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId");

                    b.ToTable("DriverNotes");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("OrderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.ItemCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.Property<Guid>("LaundryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LaundryName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LaundryId");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Laundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.LaundryItemService", b =>
                {
                    b.Property<Guid?>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LaundryId", "ItemId", "ServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("LaundryItemServices");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PickupAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PlacedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderDetail", b =>
                {
                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ItemId", "ServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.HasKey("OwnerId");

                    b.HasIndex("AddressId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionToken")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Status", b =>
                {
                    b.Property<Guid>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("StatusName")
                        .HasColumnType("longtext");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.TemporaryOrder", b =>
                {
                    b.Property<Guid>("TemporaryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PickupAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PlacedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("TemporaryOrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.HasIndex("StatusId");

                    b.ToTable("TemporaryOrders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.TemporaryOrderDetail", b =>
                {
                    b.Property<Guid?>("TemporaryOrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TemporaryOrderId", "ItemId", "ServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TemporaryOrderDetails");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Contact", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Laundry");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Driver", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.DriverNote", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("FreshlyBackendNew.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Address");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.LaundryItemService", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany()
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Laundry");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany()
                        .HasForeignKey("LaundryId");

                    b.HasOne("FreshlyBackendNew.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Customer");

                    b.Navigation("Laundry");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderDetail", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Session", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FreshlyBackendNew.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Laundry");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.TemporaryOrder", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany()
                        .HasForeignKey("LaundryId");

                    b.HasOne("FreshlyBackendNew.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Customer");

                    b.Navigation("Laundry");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.TemporaryOrderDetail", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.TemporaryOrder", "TemporaryOrder")
                        .WithMany()
                        .HasForeignKey("TemporaryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Service");

                    b.Navigation("TemporaryOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
