// <auto-generated />
using System;
using FreshlyBackendNew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshlyBackendNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418155954_AddAllRelationships")]
    partial class AddAllRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.CustomerLaundry", b =>
                {
                    b.Property<Guid>("CustomerLaundryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.HasKey("CustomerLaundryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.ToTable("CustomerLaundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItemId");

                    b.HasIndex("LaundryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.ItemService", b =>
                {
                    b.Property<Guid>("ItemServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemServiceId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ItemServices");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.Property<Guid>("LaundryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LaundryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Passcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LaundryId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Laundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PickupDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PickupTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LaundryId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Privilege", b =>
                {
                    b.Property<Guid>("PrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PrivilegeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrivilegeId");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserCustomer", b =>
                {
                    b.Property<Guid>("UserCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCustomers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserGroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserGroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroupPrivilege", b =>
                {
                    b.Property<Guid>("UserGroupPrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PrivilegeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserGroupPrivilegeId");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupPrivileges");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserLaundry", b =>
                {
                    b.Property<Guid>("UserLaundryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserLaundryId");

                    b.HasIndex("LaundryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLaundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.CustomerLaundry", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("CustomerLaundries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("CustomerLaundries")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laundry");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Feedback", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laundry");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("Items")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laundry");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.ItemService", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany("ItemServices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Service", "Service")
                        .WithMany("ItemServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Owner", "Owner")
                        .WithOne("Laundry")
                        .HasForeignKey("FreshlyBackendNew.Models.Laundry", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("Orders")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laundry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.OrderItem", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Payment", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("FreshlyBackendNew.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.UserGroup", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserCustomer", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Customer", "Customer")
                        .WithMany("UserCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.User", "User")
                        .WithMany("UserCustomers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroupPrivilege", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Privilege", "Privilege")
                        .WithMany("UserGroupPrivileges")
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.UserGroup", "UserGroup")
                        .WithMany("UserGroupPrivileges")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserLaundry", b =>
                {
                    b.HasOne("FreshlyBackendNew.Models.Laundry", "Laundry")
                        .WithMany("UserLaundries")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshlyBackendNew.Models.User", "User")
                        .WithMany("UserLaundries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laundry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Customer", b =>
                {
                    b.Navigation("CustomerLaundries");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");

                    b.Navigation("UserCustomers");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Item", b =>
                {
                    b.Navigation("ItemServices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Laundry", b =>
                {
                    b.Navigation("CustomerLaundries");

                    b.Navigation("Feedbacks");

                    b.Navigation("Items");

                    b.Navigation("Orders");

                    b.Navigation("UserLaundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Owner", b =>
                {
                    b.Navigation("Laundry")
                        .IsRequired();
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Privilege", b =>
                {
                    b.Navigation("UserGroupPrivileges");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.Service", b =>
                {
                    b.Navigation("ItemServices");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserCustomers");

                    b.Navigation("UserLaundries");
                });

            modelBuilder.Entity("FreshlyBackendNew.Models.UserGroup", b =>
                {
                    b.Navigation("UserGroupPrivileges");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
