using FreshlyBackendNew.DTOs;
using FreshlyBackendNew.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;
using System.Threading.Tasks;

namespace FreshlyBackendNew.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RejectedItemController : ControllerBase
    {
        private readonly IRejectedItemService _rejectedItemService;
        private readonly IOrderDetailService _orderDetailService;

        public RejectedItemController(IRejectedItemService rejectedItemService, IOrderDetailService orderDetailService)
        {
            _rejectedItemService = rejectedItemService;
            _orderDetailService = orderDetailService;
        }

        //lasini-get rejecteditems by orderid
        [HttpGet("order/{orderId}/rejected-items")]
        public async Task<IActionResult> GetRejectedItemsByOrderId(Guid orderId)
        {
            var items = await _rejectedItemService.GetRejectedItemsByOrderIdAsync(orderId);
            return Ok(items);
        }



        // GET: api/RejectedItem/{laundryId}/{rejectedItemId}
        [HttpGet("{laundryId:guid}/{rejectedItemId:guid}")]
        public async Task<IActionResult> GetRejectedItemById(Guid laundryId, Guid rejectedItemId)
        {
            var dto = await _rejectedItemService.GetRejectedItemByIdAsync(rejectedItemId);
            if (dto == null || dto.LaundryId != laundryId)
                return NotFound($"RejectedItem with RejectedItemId '{rejectedItemId}' and LaundryId '{laundryId}' not found.");

            return Ok(dto);
        }

        // POST: api/RejectedItem/{laundryId}
        [HttpPost("{laundryId:guid}")]
        public async Task<IActionResult> CreateRejectedItem(Guid laundryId, [FromBody] CreateRejectedItemDTO createDto)
        {
            if (createDto == null)
                return BadRequest("RejectedItem data is null.");

            var rejectedItemDto = new RejectedItemDTO
            {
                // rejectedItemId is not set here, will be generated by backend
                LaundryId = laundryId,
                OrderId = createDto.OrderId,
                ItemId = createDto.ItemId,
                ServiceId = createDto.ServiceId,
                ItemName = createDto.ItemName,
                Quantity = createDto.Quantity,
                Reason = createDto.Reason,
                RejectedBy = createDto.RejectedBy,
                RejectedAt = createDto.RejectedAt
            };

            var createdDto = await _rejectedItemService.AddRejectedItemAsync(rejectedItemDto);

            return CreatedAtAction(nameof(GetRejectedItemById), new { laundryId = createdDto.LaundryId, rejectedItemId = createdDto.RejectedItemId }, createdDto);
        }

        // GET: api/RejectedItem/laundry/{laundryId}
        [HttpGet("laundry/{laundryId:guid}")]
        public async Task<IActionResult> GetRejectedItemsByLaundryId(Guid laundryId)
        {
            var items = await _rejectedItemService.GetRejectedItemsByLaundryIdAsync(laundryId);
            if (items == null || !items.Any())
                return NotFound($"No rejected items found for LaundryId: {laundryId}");
            return Ok(items);
        }

        // GET: api/RejectedItem/{orderId}/total
        [HttpGet("{orderId:guid}/total")]
        public async Task<IActionResult> GetOrderTotal(Guid orderId)
        {
            var total = await _orderDetailService.CalculateOrderTotalAsync(orderId);
            return Ok(new { OrderId = orderId, TotalAmount = total });
        }
    }

    }
